version: '3.8'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_container
    command: --thread_stack=256K
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  mysql_data:
