export const indexDummy = [
  {
    Table: 'sample',
    Non_unique: 0,
    Key_name: 'PRIMARY',
    Seq_in_index: 1,
    Column_name: 'id',
    Collation: 'A',
    Cardinality: 3,
    Sub_part: null,
    Packed: null,
    Null: '',
    Index_type: 'BTREE',
    Comment: '',
    Index_comment: '',
    Visible: 'YES',
    Expression: null,
  },
  {
    Table: 'sample',
    Non_unique: 0,
    Key_name: 'id',
    Seq_in_index: 1,
    Column_name: 'id',
    Collation: 'A',
    Cardinality: 3,
    Sub_part: null,
    Packed: null,
    Null: '',
    Index_type: 'BTREE',
    Comment: '',
    Index_comment: '',
    Visible: 'YES',
    Expression: null,
  },
  {
    Table: 'sample',
    Non_unique: 1,
    Key_name: 'id_contents_idx',
    Seq_in_index: 1,
    Column_name: 'id',
    Collation: 'A',
    Cardinality: 3,
    Sub_part: null,
    Packed: null,
    Null: '',
    Index_type: 'BTREE',
    Comment: '',
    Index_comment: '',
    Visible: 'YES',
    Expression: null,
  },
  {
    Table: 'sample',
    Non_unique: 1,
    Key_name: 'id_contents_idx',
    Seq_in_index: 2,
    Column_name: 'content',
    Collation: 'A',
    Cardinality: 3,
    Sub_part: null,
    Packed: null,
    Null: 'YES',
    Index_type: 'BTREE',
    Comment: '',
    Index_comment: '',
    Visible: 'YES',
    Expression: null,
  },
];
